---
title: "HW1: Sequoia National Park Climate Extremes"
author: "Katheryn Moya"
date: "4/14/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(lubridate)
```


```{r}
# read in data
sequoia_clim <- read_csv(here("HW1", "AshMt_GHCND_1927_2020.csv"))  %>% 
  janitor::clean_names()

# convert date to date class using lubridate
as.Date(sequoia_clim$date)

```

Deal with NAs
```{r}
### max temp
## values are either NA or not reasonable for that location (here, below 30F)
fillrow = which(is.na(sequoia_clim$tmax) | sequoia_clim$tmax <= 30)
fillrow = fillrow[2:length(fillrow)]
sequoia_clim$tmax[fillrow]=(sequoia_clim$tmax[fillrow+1]+sequoia_clim$tmax[fillrow-1])/2
ggplot(sequoia_clim, aes(date, sequoia_clim$tmax))+
  geom_line()+ 
  labs(y="Daily Maximum Temperature (degrees F)", x="Date")

### min temp
## appears that there is at least one min temp value that is incorrect
fillrow = which(is.na(sequoia_clim$tmin) | sequoia_clim$tmin <= 15)
fillrow = fillrow[2:length(fillrow)]
sequoia_clim$tmin[fillrow]=(sequoia_clim$tmin[fillrow+1]+sequoia_clim$tmin[fillrow-1])/2
ggplot(sequoia_clim, aes(date, sequoia_clim$tmin))+
  geom_line()+ 
  labs(y="Daily Maximum Temperature (degrees F)", x="Date")

### precip
fillrow = which((is.na(sequoia_clim$prcp)) & sequoia_clim$tmax >= 70)
## fill in data in the missing rows with zeros
sequoia_clim$prcp[fillrow]=0
```


## Extreme metrics: number of freezing days

Freezing days are defined as the number of days (per year) with minimum temperatures below freezing (32 degrees F)

```{r}
# assign a new field to the climate table called "freeze" using an `ifelse` statement

sequoia_clim$freeze <- ifelse(sequoia_clim$tmin <= 32, 1, 0) # if yes, value of 1, if no, value of 0

# group data by year and put into a new dataframe
sequoia_freeze = sequoia_clim %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  summarize(n_freeze =sum(freeze, na.rm = T)) %>%
  drop_na()  

# sequoia_freeze$dt = unique(year) #unsure what to do about this, was in sam's code
    ### Yeah idk her code was weird in parts. She's trying to create a column
    ### with just the year, but I just did that with mutate and lubridate
    ### in the code above. 


# plot the number of freezing days between 1927 and 2020
freeze_days <- ggplot(data = sequoia_freeze, aes(x = year, y = n_freeze)) +
  geom_point(col = 'dodgerblue4', size = 1.6, alpha = 0.5) +
  labs(x = element_blank(),
       y = "Days under 32 F (n)")+
  stat_smooth(method = "lm", col = "dodgerblue4") +
  theme_minimal()+
  theme(
    axis.title.y = element_text(vjust = 2, size = 11, face = 'bold'),
    axis.text.x = element_text(size = 11, face = 'bold'),
    axis.text.y = element_text(size = 11)
  )

## save plot
# ggsave(filename = 'freeze_days_sequoia.jpeg', plot = freeze_days, width = 8, height = 5, units = "in")


```

## Extreme metrics: hottest day of the year
```{r}
# how many days over 100?
sequoia_clim$over_100 <- ifelse(sequoia_clim$tmax >= 100, 1, 0)

# group data by year and put into a new dataframe
sequoia_peak <- sequoia_clim %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  summarize(hottest_day = max(tmax),
            over_100 = sum(over_100)) %>%
  drop_na()  


# plot the hottest day of the year  between 1927 and 2020
hottest_day <- ggplot(data = sequoia_peak, aes(x = year, y = hottest_day)) +
  geom_point(col = 'firebrick3', size = 1.6, alpha = 0.5) +
  labs(x = element_blank(),
       y = "Temperature of Hottest Day of the Year (F)")+
  stat_smooth(method = "lm", col = "firebrick") +
  theme_minimal()+
  theme(
    axis.title.y = element_text(vjust = 2, size = 11, face = 'bold'),
    axis.text.x = element_text(size = 11, face = 'bold'),
    axis.text.y = element_text(size = 11)
  )

# plot number of days over 100 between 1927 and 2020
days_over_100 <- ggplot(data = sequoia_peak, aes(x = year, y = over_100)) +
  geom_point(col = 'firebrick3', size = 1.6, alpha = 0.5) +
  labs(x = element_blank(),
       y = "Days over 100 F (n)")+
  stat_smooth(method = "lm", col = "firebrick") +
  theme_minimal()+
  theme(
    axis.title.y = element_text(vjust = 2, size = 11, face = 'bold'),
    axis.text.x = element_text(size = 11, face = 'bold'),
    axis.text.y = element_text(size = 11)
  )

## save plot
ggsave(filename = 'freeze_days_sequoia.jpeg', plot = freeze_days, width = 8, height = 5, units = "in")
```

```{r}
### combine into one?
combo <- plot_grid(freeze_days, days_over_100,
            align = 'V',
            ncol = 1,
            labels = c('A', 'B'),
            hjust = -.5,
            vjust = 1.5)

## save plot
ggsave(filename = 'extreme_days_sequoia.jpeg', plot = combo, width = 8, height = 6, units = "in")
```



## Extreme metrics: (something with precipitation/ drought?)
```{r}
# return period

# assign a new field to the climate table called "flood" using an `ifelse` statement
sequoia_clim$flood <- ifelse(sequoia_clim$prcp >= 1, 1, 0) 
mutate(sequoia_clim, year = lubridate::year(date))

nyrs = length(unique(year(sequoia_clim$date)))
  # [1] 94
retper=(nyrs+1)/sum(sequoia_clim$flood,na.rm=TRUE)
  # [1] 0.138484
```


